/* babeldb: native Node.js binding (napi-rs v3). */
/* The types from this header come from dts-header.d.ts; the declarations
   after it are generated by NAPI-RS from src/*.rs (napi build). */
/* eslint-disable */
/// <reference types="node" />

/**
 * A key: raw bytes (`Buffer` / `Uint8Array`) or a string, stored as its UTF-8
 * bytes. Keys are compared bytewise; 1 to 4096 bytes.
 */
export type Key = Buffer | Uint8Array | string

/** A value: raw bytes or a string (UTF-8). Values are always returned as `Buffer`. */
export type Value = Buffer | Uint8Array | string

/**
 * When a write's promise resolves:
 * - `'immediate'` (default): once the write is durable. Concurrent writes
 *   share one commit (group commit), so they share its WAL write.
 * - `'buffered'`: once it is committed and visible; it becomes durable within
 *   ~100 ms (or before 64 MiB of writes are pending), on `sync()`, on
 *   `close()` and when the process exits. A crash or a kill may lose the
 *   last ~100 ms of acknowledged writes.
 */
export type Durability = 'immediate' | 'buffered'

export interface OpenOptions {
  /** Default `'immediate'`. */
  durability?: Durability
}

export interface PutOptions {
  /** Write only if the key does not exist (else `CONFLICT`). */
  ifAbsent?: boolean
  /**
   * Write only if the key's current revision is exactly this one (else
   * `CONFLICT`). Cannot be combined with `ifAbsent`.
   */
  ifRevision?: bigint | number
}

export interface DeleteOptions {
  /**
   * Delete only if the key's current revision is exactly this one (else
   * `CONFLICT`, also when the key does not exist).
   */
  ifRevision?: bigint | number
}

export interface ScanOptions {
  /** Only keys starting with these bytes. Cannot be combined with `start` / `end`. */
  prefix?: Key
  /** First key of the range (inclusive). */
  start?: Key
  /** End of the range (exclusive). */
  end?: Key
  /** Descending key order. */
  reverse?: boolean
  /** At most this many records (with `reverse`: the last ones). `0` or absent: no limit. */
  limit?: number | bigint
}

/** An operation of `batch()`. */
export type BatchOp =
  | { type: 'put'; key: Key; value: Value }
  | { type: 'del'; key: Key }

/**
 * `code` of the errors babeldb throws / rejects with:
 * - `CONFLICT`: an `ifAbsent` / `ifRevision` expectation failed; nothing was written.
 * - `CLOSED`: the database is closed.
 * - `ALREADY_OPEN`: the directory is already open (in this process, or in another one).
 * - `INVALID_ARGUMENT`: a malformed argument, or one the store refuses (empty
 *   key, key or value over the limits, `prefix` with `start`/`end`, ...).
 * - the other codes name the store error: `IO`, `BACKEND`, `FORMAT`,
 *   `INTEGRITY`, `UNKNOWN_CODEC`, `UNKNOWN_GENERATOR`, `MISSING_DEPENDENCY`,
 *   `ID_EXHAUSTED`, `UNSUPPORTED`, `UNKNOWN`; `INTERNAL` is a binding bug.
 */
export type ErrorCode =
  | 'CONFLICT'
  | 'CLOSED'
  | 'ALREADY_OPEN'
  | 'INVALID_ARGUMENT'
  | 'IO'
  | 'BACKEND'
  | 'FORMAT'
  | 'INTEGRITY'
  | 'UNKNOWN_CODEC'
  | 'UNKNOWN_GENERATOR'
  | 'MISSING_DEPENDENCY'
  | 'ID_EXHAUSTED'
  | 'UNSUPPORTED'
  | 'UNKNOWN'
  | 'INTERNAL'

/** The shape of every error babeldb throws or rejects with. */
export interface BabelDbError extends Error {
  code: ErrorCode
}

