/* babeldb: native Node.js binding (napi-rs v3). */
/* The types from this header come from dts-header.d.ts; the declarations
   after it are generated by NAPI-RS from src/*.rs (napi build). */
/* eslint-disable */
/// <reference types="node" />

/**
 * A key: raw bytes (`Buffer` / `Uint8Array`) or a string, stored as its UTF-8
 * bytes. Keys are compared bytewise; 1 to 4096 bytes.
 */
export type Key = Buffer | Uint8Array | string

/** A value: raw bytes or a string (UTF-8). Values are always returned as `Buffer`. */
export type Value = Buffer | Uint8Array | string

/**
 * When a write's promise resolves:
 * - `'immediate'` (default): once the write is durable. Concurrent writes
 *   share one commit (group commit), so they share its WAL write.
 * - `'buffered'`: once it is committed and visible; it becomes durable within
 *   ~100 ms (or before 64 MiB of writes are pending), on `sync()`, on
 *   `close()` and when the process exits. A crash or a kill may lose the
 *   last ~100 ms of acknowledged writes.
 */
export type Durability = 'immediate' | 'buffered'

export interface OpenOptions {
  /** Default `'immediate'`. */
  durability?: Durability
}

export interface PutOptions {
  /** Write only if the key does not exist (else `CONFLICT`). */
  ifAbsent?: boolean
  /**
   * Write only if the key's current revision is exactly this one (else
   * `CONFLICT`). Cannot be combined with `ifAbsent`.
   */
  ifRevision?: bigint | number
}

export interface DeleteOptions {
  /**
   * Delete only if the key's current revision is exactly this one (else
   * `CONFLICT`, also when the key does not exist).
   */
  ifRevision?: bigint | number
}

export interface ScanOptions {
  /** Only keys starting with these bytes. Cannot be combined with `start` / `end`. */
  prefix?: Key
  /** First key of the range (inclusive). */
  start?: Key
  /** End of the range (exclusive). */
  end?: Key
  /** Descending key order. */
  reverse?: boolean
  /** At most this many records (with `reverse`: the last ones). `0` or absent: no limit. */
  limit?: number | bigint
}

/** An operation of `batch()`. */
export type BatchOp =
  | { type: 'put'; key: Key; value: Value }
  | { type: 'del'; key: Key }

/**
 * `code` of the errors babeldb throws / rejects with:
 * - `CONFLICT`: an `ifAbsent` / `ifRevision` expectation failed; nothing was written.
 * - `CLOSED`: the database is closed.
 * - `ALREADY_OPEN`: the directory is already open (in this process, or in another one).
 * - `INVALID_ARGUMENT`: a malformed argument, or one the store refuses (empty
 *   key, key or value over the limits, `prefix` with `start`/`end`, ...).
 * - the other codes name the store error: `IO`, `BACKEND`, `FORMAT`,
 *   `INTEGRITY`, `UNKNOWN_CODEC`, `UNKNOWN_GENERATOR`, `MISSING_DEPENDENCY`,
 *   `ID_EXHAUSTED`, `UNSUPPORTED`, `UNKNOWN`; `INTERNAL` is a binding bug.
 */
export type ErrorCode =
  | 'CONFLICT'
  | 'CLOSED'
  | 'ALREADY_OPEN'
  | 'INVALID_ARGUMENT'
  | 'IO'
  | 'BACKEND'
  | 'FORMAT'
  | 'INTEGRITY'
  | 'UNKNOWN_CODEC'
  | 'UNKNOWN_GENERATOR'
  | 'MISSING_DEPENDENCY'
  | 'ID_EXHAUSTED'
  | 'UNSUPPORTED'
  | 'UNKNOWN'
  | 'INTERNAL'

/** The shape of every error babeldb throws or rejects with. */
export interface BabelDbError extends Error {
  code: ErrorCode
}


/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * An open babeldb database: one directory, opened with `open()`.
 *
 * Every async method runs on the libuv threadpool and never blocks the
 * event loop; its `*Sync` twin does the same work on the calling thread
 * (for scripts). Concurrent calls are safe. Calls that are not awaited run
 * in no particular order: await a write before an operation that must see
 * it.
 */
export declare class Database {
  /**
   * Write `value` under `key` and resolve with the new revision once the
   * write is committed: durable in `'immediate'` mode, visible (durable
   * within ~100 ms) in `'buffered'` mode. Concurrent writes share commits.
   *
   * `ifAbsent: true` writes only if the key does not exist; `ifRevision`
   * only if its current revision is exactly that one. A failed expectation
   * rejects with `code === 'CONFLICT'` and writes nothing.
   */
  put(key: Key, value: Value, options?: PutOptions): Promise<bigint>
  /**
   * Synchronous {@link Database.put}: blocks the calling thread until the
   * write is committed; returns the new revision.
   */
  putSync(key: Key, value: Value, options?: PutOptions): bigint
  /** The current value of `key`, or `null` when it does not exist. */
  get(key: Key): Promise<Buffer | null>
  /** Synchronous {@link Database.get}. */
  getSync(key: Key): Buffer | null
  /**
   * Delete `key`; resolves `true` if a live record was deleted, `false` if
   * there was none. With `ifRevision`, deletes only if the current revision
   * is exactly that one (a missing key then conflicts too): otherwise
   * rejects with `code === 'CONFLICT'`. Durability as for `put`.
   */
  delete(key: Key, options?: DeleteOptions): Promise<boolean>
  /** Synchronous {@link Database.delete}. */
  deleteSync(key: Key, options?: DeleteOptions): boolean
  /**
   * `[key, value]` pairs in key order (bytewise), or descending with
   * `reverse`. Bounds: `prefix`, or `start` (inclusive) and/or `end`
   * (exclusive); `prefix` cannot be combined with `start`/`end`
   * (`INVALID_ARGUMENT`). `limit` caps the number of pairs (with
   * `reverse`: the last ones); `0` or absent = no limit. Reads one
   * consistent snapshot.
   */
  scan(options?: ScanOptions): Promise<Array<[Buffer, Buffer]>>
  /** Synchronous {@link Database.scan}. */
  scanSync(options?: ScanOptions): Array<[Buffer, Buffer]>
  /**
   * The keys a {@link Database.scan} with the same options would return
   * (values are not read).
   */
  keys(options?: ScanOptions): Promise<Buffer[]>
  /** Synchronous {@link Database.keys}. */
  keysSync(options?: ScanOptions): Buffer[]
  /**
   * Apply `ops` atomically, in order, in ONE commit that is durable when
   * the promise resolves, in both durability modes (`Db::write_batch`).
   * All or nothing: if any operation is malformed or invalid (an empty
   * key, a key or value over the limits...) nothing is written and the
   * promise rejects (`INVALID_ARGUMENT`, or `IO`... if the commit fails).
   * A later operation sees the effects of earlier ones on the same key.
   *
   * Resolves with one entry per operation: for a put, its new revision;
   * for a `del`, the revision of the deleted record, or `null` if the key
   * did not exist. The batch is its own commit: it does not ride the group
   * commits of `put`/`delete` (and it makes earlier buffered writes
   * durable too).
   */
  batch(ops: BatchOp[]): Promise<Array<bigint | null>>
  /** Synchronous {@link Database.batch}. */
  batchSync(ops: BatchOp[]): Array<bigint | null>
  /**
   * Resolves once every write acknowledged before this call is durable
   * (in `'buffered'` mode it forces the flush; in `'immediate'` mode they
   * already are).
   */
  sync(): Promise<void>
  /**
   * Close the database. Operations already called complete first
   * (waiting for them blocks this thread), buffered writes become durable,
   * and the directory is released: it can be opened again as soon as this
   * returns. Afterwards every method throws (sync) or rejects (async) with
   * `code === 'CLOSED'`. Closing a closed database does nothing.
   */
  close(): void
  /** `true` once `close()` was called (or the process is exiting). */
  get closed(): boolean
  /**
   * The database directory (absolute, canonical). The write-ahead log is
   * the file `<path>.wal` next to it.
   */
  get path(): string
  /** The durability mode the database was opened with. */
  get durability(): Durability
}

/**
 * The 8-byte prefix shared by every message key of `channel`: scan it with
 * `{ prefix: channelPrefix(c), reverse: true, limit: n }` for the n newest
 * messages.
 */
export declare function channelPrefix(channel: bigint | number): Buffer

/**
 * The 16-byte key of chat message `id` in `channel`: `channel` (u64
 * big-endian) followed by `id` (u64 big-endian). Keys sort by channel, then
 * by id: with growing ids (snowflakes), the newest messages of a channel
 * are a reverse scan of {@link channelPrefix} with a limit.
 */
export declare function messageKey(channel: bigint | number, id: bigint | number): Buffer

/**
 * Open (or create) the database stored in directory `path`: an fjall
 * LSM-tree in `path` plus a write-ahead log next to it (`<path>.wal`).
 *
 * Only one handle per directory may be open in a process: opening an open
 * directory again throws at once with `code === 'ALREADY_OPEN'` (so does a
 * directory another process has open). Throws `INVALID_ARGUMENT` for bad
 * options and `IO` when the directory cannot be created.
 *
 * Handles still open when the process exits (a natural exit or
 * `process.exit()`) are closed then, so the writes they accepted (buffered
 * ones included) are durable. A crash or a kill may lose the buffered
 * writes of the last ~100 ms.
 */
export declare function open(path: string, options?: OpenOptions): Database

/**
 * Inverse of {@link messageKey}: `[channel, id]`, or `null` when `key` is
 * not 16 bytes long.
 */
export declare function parseMessageKey(key: Key): [bigint, bigint] | null
